AUTHORIZED_FACES_PATH = "faces"
INIT_URL = "https://fitnessneo.ru/get-faceid-users/"
UPDATE_URL = "https://fitnessneo.ru/get-new-faceid-users/"
OPENING_EVENT_URL = "https://fitnessneo.ru/add-event/"
LOGS_PATH = "logs"
SAVE_RECOG_IMAGE = "recog.png"
SAVE_USER_IMAGE = "user_log"
DISPLAY_WIDTH = 1920
DISPLAY_HEIGHT = 1080
EXIT_CAMERAS = (1, )
