AUTHORIZED_FACES_PATH = "faces"
INIT_URL = "https://fitnessneo.ru/get-faceid-users/"
UPDATE_URL = "https://fitnessneo.ru/get-new-faceid-users/"
OPENING_EVENT_URL = "https://fitnessneo.ru/add-event/"
CASCADE_PATH = r"haarcascade_frontalface_default.xml"
LOGS_PATH = "logs"
SAVE_USER_IMAGE = ""
DISPLAY_WIDTH = 1920
DISPLAY_HEIGHT = 1080
DETECTION_ZONE_SIZE = .5
RECT_LINES = 8
RECT_LINE_MIN = 13
EXIT_CAMERAS = (0, )
DELAYS = (1, 0)
