AUTHORIZED_FACES_PATH = "/var/recog/faces"
INIT_URL = "https://zal-neo.isamara.ru/get-faceid-users/"
UPDATE_URL = "https://zal-neo.isamara.ru/get-new-faceid-users/"
OPENING_EVENT_URL = "https://zal-neo.isamara.ru/add-event/"
LOGS_PATH = "/var/recog/logs"
CASCADE_PATH = r"/var/recog/haarcascade_frontalface_default.xml"
SAVE_USER_IMAGE = ""
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 480
DETECTION_ZONE_SIZE = .9
RECT_LINES = 10
RECT_LINE_MIN = 13
FLIP_Y = (0, 1)
FLIP_X = (1, )
DELAYS = (1, 0, 0)
