AUTHORIZED_FACES_PATH = "/var/recog/faces"
INIT_URL = "https://fitnessneo.ru/get-faceid-users/"
UPDATE_URL = "https://fitnessneo.ru/get-new-faceid-users/"
LOGS_PATH = "/var/recog/logs"
SAVE_RECOG_IMAGE = ""
